### PR TITLE
merge from origin master

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[d1a27c3](https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis/pull/5/commits/d1a27c386e8ac939202c5b265d07d9ee94bbab82)_: 

:clock10: **Preparing**: average preparing time is not available, there is no data for this repository.

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[d1a27c3](https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis/pull/5/commits/d1a27c386e8ac939202c5b265d07d9ee94bbab82)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-) |

<a name=""></a>
### []()
 - **Line 108**: **[Error]** Restore nuget package W:\kwoe-s\.optemp\dependentPackages\Microsoft.OpenPublishing.CommonPlugins\packages.config in folder:W:\kwoe-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;1.0.154-alpha&#39; of package &#39;Microsoft.OpenPublishing.CommonPlugins&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.154-alpha&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://www.myget.org/F/op-dev/api/v2: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.154-alpha&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2&#39;.
 - **Line 290**: **[Error]** Restore dependent packages failed

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C12%5C10%5Cdee5e62b-9939-fd19-8969-a01dd2ba3a45%5CPullRequest%5C201812100800261222-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YATLFUFN4PxGMhB%2F20UrLoGPtSjg%2B3YfEAd4xsPlsYM%3D&st=2018-12-10T07%3A56%3A10Z&se=2019-01-10T08%3A01%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[d1a27c3](https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis/pull/5/commits/d1a27c386e8ac939202c5b265d07d9ee94bbab82)_: 

:clock10: **Preparing**: average preparing time is not available, there is no data for this repository.

**Comment by v-peliao-zz** [comment]
OPS Build status updates of commit _[d1a27c3](https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis/pull/5/commits/d1a27c386e8ac939202c5b265d07d9ee94bbab82)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-) |

<a name=""></a>
### []()
 - **Line 108**: **[Error]** Restore nuget package W:\gpaq-s\.optemp\dependentPackages\Microsoft.OpenPublishing.CommonPlugins\packages.config in folder:W:\gpaq-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;1.0.154-alpha&#39; of package &#39;Microsoft.OpenPublishing.CommonPlugins&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.154-alpha&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://www.myget.org/F/op-dev/api/v2: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.154-alpha&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2&#39;.
 - **Line 290**: **[Error]** Restore dependent packages failed

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C12%5C10%5Cdee5e62b-9939-fd19-8969-a01dd2ba3a45%5CPullRequest%5C201812100802142970-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tcpEv%2BxtqtLWJT6TrN7uemcCSd7rnLomRe29CH3hPrQ%3D&st=2018-12-10T07%3A58%3A23Z&se=2019-01-10T08%3A03%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
